#ARG BUILD_FROM
#FROM $BUILD_FROM
# Use the official Golang image with Go 1.18 for building the application
FROM golang:1.18-alpine

# Install necessary dependencies
RUN apk add --no-cache bash jq

# Set the current working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files
COPY go.mod ./

# Download dependencies
RUN go mod download

# Copy the source code
COPY main.go .
COPY template.html .
COPY static ./static
COPY config.json /data/config.json

# Build the Go app
RUN go build -o  bin-waste-collection main.go
# Build the Go app
RUN go build -o  /app/bin-waste-collection main.go

# Copy the run script
COPY run.sh /app/run.sh
RUN chmod +x /app/run.sh

# Verify the run.sh script is present
RUN ls -l /app

# Start the application using the run.sh script
CMD ["/app/run.sh"]