# Start from a base Go image
FROM golang:1.18-alpine AS build

# Install necessary dependencies
RUN apk add --no-cache bash jq ca-certificates

# Set the working directory
WORKDIR /app

# Copy Go module files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the Go source code and build it
COPY main.go ./
RUN go build -o bin-waste-collection main.go

# Use a smaller base image for the runtime
FROM alpine:3.16

# Copy the built binary and necessary files
COPY --from=build /app/bin-waste-collection /app/bin-waste-collection
COPY --from=build /app/template.html /app/template.html
COPY --from=build /app/static /app/static
COPY --from=build /app/config.json /app/config.json
COPY --from=build /app/run.sh /app/run.sh

# Make the run.sh file executable
RUN chmod +x /app/run.sh

# Use the run.sh script as the entry point
ENTRYPOINT ["/app/run.sh"]